In [0]:
# Code to read file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticating email
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
import logging
logging.getLogger('googleapicliet.discovery_cache').setLevel(logging.ERROR)
#2.1 Get the file
downloaded = drive.CreateFile({'id':'1tJsRW4y-H_ixYKwKGVQHXmpCr8Kt65uc'}) # replace the id with id of file you want to access
downloaded.GetContentFile('Churn_Modelling.csv')

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [32]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [0]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Using TensorFlow backend.





Epoch 1/100





8000/8000 [==============================] - 2s 207us/step - loss: 0.4829 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4290 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4241 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4195 - acc: 0.8121
Epoch 5/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4171 - acc: 0.8242
Epoch 6/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4148 - acc: 0.8265
Epoch 7/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4131 - acc: 0.8320
Epoch 8/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4112 - acc: 0.8334
Epoch 9/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4104 - acc: 0.8331
Epoch 10/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4094 - acc

In [0]:
#  Making predictions and evaluating the model
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [0]:
cm

array([[1497,   98],
       [ 186,  219]])

In [0]:
print(report)

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      1595
           1       0.69      0.54      0.61       405

    accuracy                           0.86      2000
   macro avg       0.79      0.74      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [0]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)

In [0]:
new_prediction

array([[False]])

In [0]:
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()


In [0]:
mean

0.8388749947398901

In [0]:
variance

0.013946884640863147

In [0]:
# Improving the ANN

# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
              'epochs': [100, 200],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)

Epoch 1/100
7200/7200 [==============================] - 1s 81us/step - loss: 0.5625 - acc: 0.7950
Epoch 2/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.4347 - acc: 0.7971
Epoch 3/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4292 - acc: 0.7971
Epoch 4/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.4260 - acc: 0.7971
Epoch 5/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.4229 - acc: 0.7971
Epoch 6/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4200 - acc: 0.7971
Epoch 7/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.4181 - acc: 0.8142
Epoch 8/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.4171 - acc: 0.8226
Epoch 9/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.4159 - acc: 0.8242
Epoch 10/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.4151 - acc: 0.8261
Epoch 11/

In [0]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [16]:
best_accuracy

0.848125

In [15]:
best_parameters

{'batch_size': 25, 'epochs': 200, 'optimizer': 'adam'}

In [17]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 25, epochs = 200)

Epoch 1/200
8000/8000 [==============================] - 6s 710us/step - loss: 0.5525 - acc: 0.7945
Epoch 2/200
8000/8000 [==============================] - 1s 80us/step - loss: 0.4237 - acc: 0.8051
Epoch 3/200
8000/8000 [==============================] - 1s 92us/step - loss: 0.4095 - acc: 0.8245
Epoch 4/200
8000/8000 [==============================] - 1s 87us/step - loss: 0.3996 - acc: 0.8259
Epoch 5/200
8000/8000 [==============================] - 1s 94us/step - loss: 0.3911 - acc: 0.8302
Epoch 6/200
8000/8000 [==============================] - 1s 82us/step - loss: 0.3855 - acc: 0.8306
Epoch 7/200
8000/8000 [==============================] - 1s 81us/step - loss: 0.3806 - acc: 0.8299
Epoch 8/200
8000/8000 [==============================] - 1s 82us/step - loss: 0.3762 - acc: 0.8326
Epoch 9/200
8000/8000 [==============================] - 1s 88us/step - loss: 0.3728 - acc: 0.8439
Epoch 10/200
8000/8000 [==============================] - 1s 81us/step - loss: 0.3700 - acc: 0.8450
Epoch 11

In [0]:
classifier.save('ann_model.h5')

# **Load pre-trained model**

In [0]:
from keras.models import load_model
model = load_model('ann_model.h5')

In [0]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = model.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

In [28]:
new_prediction

array([[0.03763918]], dtype=float32)

In [0]:
new_prediction = (new_prediction > 0.5)

In [30]:
new_prediction

array([[False]])